version: '2'
services:

    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - "80:80"
        restart: always
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./web:/var/www/html"
        depends_on:
            - "php"
            - "mysql"
        networks:
            - backend

    php:
        build: ./etc/php
        container_name: php
        restart: always
        volumes:
            - "./web:/var/www/html"
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
        networks:
            - backend

    mysql:
        image: mysql
        container_name: mysql
        restart: always
        environment:
            - MYSQL_DATABASE=test
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=dev
            - MYSQL_PASSWORD=dev
        ports:
            - 3306:3306
        volumes:
            - ./data/db/mysql:/var/lib/mysql
        networks:
            - backend

networks:
  backend:
    driver: "bridge"
